name: Linux Acceptance Test
run-name: Linux Acceptance Test (Triggered by ${{ github.event_name }} by @${{ github.actor }})
on:
  workflow_dispatch:
    inputs:
      GPU_FAMILY:
        description: 'GPU Family'
        required: true
        type: string
      TEST_REPO:
        description: 'Test repository'
        required: true
        type: string
  workflow_call:
    inputs:
      GPU_FAMILY:
        description: 'GPU Family'
        required: true
        type: string
      TEST_REPO:
        description: 'Test repository'
        required: true
        type: string

jobs:
  test:
    runs-on: [self-hosted, Linux, docker, "${{ inputs.GPU_FAMILY }}"]
    steps:
      - name: Cleanup workspace
        run: |
          sudo rm -rf ${{github.workspace}}/*
          sudo rm -rf sudo rm -rf ${{github.workspace}}/.[!.]* ${{github.workspace}}/..?*
      - name: Check out tests
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.TEST_REPO }}
          token: ${{ secrets.TEST_REPO_TOKEN }}
          path: tests
          ref: main
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: package
      - name: Extract package
        run: unzip package/*.zip -d _install
      - name: Build Docker image
        run: >          
          docker build "tests/environments"
          -f "tests/environments/Dockerfile.ubuntu.gputest"
          -t vpl_gputestenv:ubuntu
      - name: Test package in container
        run: |
          cat >test.sh <<EOL
          #!/bin/bash
          set -o errexit
          if [[ "\$DASHBOARD_PLATFORM_SW_OPENVINO_INSTALLED" == 1 ]]; then
          . /opt/intel/openvino_2022/setupvars.sh
          fi
          set -o nounset
          . _install/etc/vpl/vars.sh

          DASHBOARD_INSTALL_ONEVPLCPU_LICENSE=gpl
          export DASHBOARD_INSTALL_ONEVPLCPU_LICENSE
          DASHBOARD_INSTALL_ONEVPL32=0
          export DASHBOARD_INSTALL_ONEVPL32
          DASHBOARD_INSTALL_ONEVPLDEBUG=0
          export DASHBOARD_INSTALL_ONEVPLDEBUG
          DASHBOARD_PLATFORM_HW_INTEGRATED_GPU="${{ inputs.GPU_FAMILY }}"
          export DASHBOARD_PLATFORM_HW_INTEGRATED_GPU
          pushd tests
          ./run.sh gen

          EOL
          chmod a+x test.sh
          docker run --rm -v $(pwd):/tmp/work -w /tmp/work --privileged vpl_gputestenv:ubuntu ./test.sh

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: linux-acceptance-${{ inputs.GPU_FAMILY }}
          path: tests/logs/*
