name: Complier Settings Windows
run-name: Complier Settings Windows (Triggered by ${{ github.event_name }} by @${{ github.actor }})
on:       
  workflow_dispatch:
  workflow_call:

jobs:
  compiler-settings-windows:
    runs-on: [self-hosted, Windows, CMake, vs2022]
    steps:
        - name: Check Out Code
          uses: actions/checkout@v3

        - name: Download Artifact
          uses: actions/download-artifact@v3
          with:
              name: windows-build
          
        - name: Unzip Artifacts
          run: |
            Expand-Archive -Path "*.zip" -DestinationPath "_install"
          
        - name: Run Compiler Settings Check
          run: |
            py -m venv venv
            venv\Scripts\activate
            py -m pip install --upgrade pip
            py -m pip install ${{ vars.COMPILER_SETTINGS_TOOL_URL }} --use-pep517
            sscb run --path "_install" --outpath "_logs" --report_name Windows

        - name: Check Security Scan Results
          continue-on-error: true
          run: |
              $result = Select-String -Path "_logs/SSCB_SCAN_results-Windows.html" -Pattern "Total Issues Identified *: 0"
              if ($result -eq $null) {
                echo "Potential security gaps identified in compiled binaries"
                exit 1
              } else{
                echo "No security gaps identified in compiled binaries"
              }

        - name: Record Artifacts
          uses: actions/upload-artifact@v3
          if: success() || failure()
          with:
              name: windows-complier_settings
              path: _logs/*
