name: Complier Settings Linux
run-name: Complier Settings Linux (Triggered by ${{ github.event_name }} by @${{ github.actor }})
on:       
  workflow_dispatch:
  workflow_call:

jobs:
  compiler-settings-linux:
    runs-on: [self-hosted, Linux, docker]
    steps:
      - name: Cleanup
        run: |
          sudo rm -rf -- ..?* .[!.]* *

      - name: Build Docker image
        run: |
          USER_ID=$(id -u ${USER})
          GROUP_ID=$(id -g ${USER})
          # Dockerfile will contain everything between <<EOL and EOL
          cat >Dockerfile <<EOL
          FROM ubuntu:22.04

          # Install python
          RUN apt-get update && apt-get install -y --no-install-recommends \
              python3 \
              python3-pip \
              python3-venv \
              && \
            rm -rf /var/lib/apt/lists/*

          # Install sscp prerequisites
          RUN apt-get update && apt-get install -y --no-install-recommends \
              binutils \
              file \
              && \
            rm -rf /var/lib/apt/lists/* 
          RUN  python3 -m pip install setuptools \
            && python3 -m pip install wheel \
            && python3 -m pip install ${{ vars.COMPILER_SETTINGS_TOOL_URL }}
          RUN groupadd -g $GROUP_ID user || true
          RUN useradd --disabled-password --gecos "" --uid $USER_ID --gid $GROUP_ID user || true
          EOL
          docker build -t vplcompiler_settings:github_runner .


      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
            name: linux-build 

      - name: Unzip Artifacts
        run: |
          unzip "*.zip" -d "_install"

      - name: Write scan script
        run: |
          cat >action.sh <<EOL 
          #!/bin/bash
          set -x
          set -o errexit ; set -o nounset
          sscb run --path _install --outpath _logs --report_name Linux
          EOL
          chmod +x action.sh

      - name: Run Compiler Settings Check
        run: |
          docker run --rm -v $PWD:/working -w/working vplcompiler_settings:github_runner /working/action.sh

      - name: Check Security Scan Results
        run: |
          if grep -q "Total Issues Identified *: *0" _logs/SSCB_SCAN_results-Linux.html ; then
            echo "No security gaps identified in compiled binaries"
          else
            echo "Potential security gaps identified in compiled binaries"
            exit 1
          fi

      - name: Record Artifacts
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
            name: linux-complier_settings
            path: _logs/*
