name: Windows
run-name: Windows (Triggered by ${{ github.event_name }} by @${{ github.actor }})
on:
  workflow_dispatch:
    inputs:
      TEST_REPO:
        description: 'Test repository'
        required: true
        type: string
  workflow_call:
    inputs:
      TEST_REPO:
        description: 'Test repository'
        required: true
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - config: Release
            package: windows-build
          - config: Debug
            package: windows-build-debug
    name: ${{ matrix.config }} Build
    uses: ./.github/workflows/build-windows.yaml
    secrets: inherit
    with:
      BUILD_CONFIG: ${{ matrix.config }}
      PACKAGE_NAME: ${{ matrix.package }}
  acceptance:
    needs: build
    uses: ./.github/workflows/acceptance-test-windows.yaml
    strategy:
      fail-fast: false
      matrix:
          accelerator: [gen12.5, gen9.5]
          package: [windows-build]
          nonfatal: [false]
          include:
            # these cases are non-blocking fails
            - accelerator: gen12.5
              package: windows-build-debug
              nonfatal: true
            - accelerator: gen9.5
              package: windows-build-debug
              nonfatal: true
    name: Acceptance Test on ${{ matrix.accelerator }}
    secrets: inherit
    with:
      TEST_REPO: ${{ inputs.TEST_REPO }}
      GPU_FAMILY: ${{ matrix.accelerator }}
      PACKAGE: ${{ matrix.package }}
      DEBUG: ${{ contains(matrix.package, 'debug') }}
      NONFATAL: ${{ matrix.nonfatal }}
