name: Evaluate Pull Request
run-name: Evaluate Pull Request (Triggered by ${{ github.event_name }} by @${{ github.actor }})
on:
  push:
    branches:
      - "test/**"
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yaml
    secrets: inherit
  ip-leak-scan:
    name: IP Leak Scan
    uses: ./.github/workflows/ip-leak-scan.yaml
    secrets: inherit
    with:
        IPLDB_TOOL_URL: '${{ vars.IPLDB_TOOL_URL }}'
  build-windows:
    name: Windows Build
    uses: ./.github/workflows/build-windows.yaml
    secrets: inherit
  build-linux:
    name: Linux Build
    uses: ./.github/workflows/build-linux.yaml
    secrets: inherit
  